site_name: BridgeFoundry Operations
docs_dir: docs/
repo_url: https://github.com/bridgefoundry/operations
theme: 'readthedocs'
pages:
- "Home": 'index.md'
- "Roles":
    - "Overview": 'roles/README.md'
    - "Administrative support policies" : 'roles/administrative-support-policies.md'
    - "Bridge leader policies": 'roles/bridge-leader-policies.md'
    - "Chapter leader policies": 'roles/chapter-leader-policies.md'
    - "Program leader policies": 'roles/program-leader-policies.md'
    - "Volunteer fundraiser policies": 'roles/volunteer-fundraiser-policies.md'
- "Fundraising":
    - "Overview": 'fundraising/README.md'
    - "Employer match": 'fundraising/employer-match.md'
    - "Invoice request": 'fundraising/invoice-request.md'
    - "PayPal button": 'fundraising/paypal-button.md'
    - "Unrestricted funds": 'fundraising/unrestricted-funds.md'
- "Grants":
    - "Overview": 'grants/README.md'
    - "Funded grants": 'grants/funded-grants.md'
    - "Seed grants": 'grants/seed-grants.md'
- "Using funds":
    - "Overview": 'using-funds/README.md'
    - "Approved expenses policy": 'using-funds/approved-expenses-policy.md'
    - "Direct pay": 'using-funds/direct-pay.md'
    - "Expense reports": 'using-funds/expense-reports.md'
    - "Pex cards": 'using-funds/pex-cards.md'
- "Monitoring funds": 'monitoring-funds.md'
- "Internal process":
    - "Overview": 'internal-process/README.md'
    - "Grant decision guidelines": 'internal-process/grant-decision-guidelines.md'
- "Corporate Docs":
    - "Overview": 'corporate-docs/README.md'
